services:
  horizondb:
    platform: linux/x86_64
    image: mysql:8
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_DATABASE: horizon
      MYSQL_USER: vapor
      MYSQL_PASSWORD: vapor
      MYSQL_ROOT_PASSWORD: horizon
      MYSQL_TCP_PORT: 3306
    volumes:
      - mysqldata8:/var/lib/mysql/

    networks:
      - horizon
  migration: 
    depends_on:
      horizondb:
        condition: service_healthy
    build:
      context: .
      containerfile: Containerfile
    env_file:
      - .env
    command: |
      /bin/sh -c "
        set -e
        php artisan migrate --seed
      "
    networks:
      - horizon
  app:
    depends_on:
      migration:
        condition: service_completed_successfully
    restart: always
    build:
      context: .
      containerfile: Containerfile
    ports:
      - "9000:9000"
    expose:
      - "9000"
    env_file:
      - .env
    command: |
      /bin/sh -c "
        set -e
        php artisan serve --host 0.0.0.0 --port 9000
      "
    networks:
      - horizon 
  horizon:
    depends_on:
      migration:
        condition: service_completed_successfully
    restart: always
    build:
      context: .
      containerfile: Containerfile
    env_file:
      - .env
    command: |
      /bin/sh -c "
        set -e
        php artisan horizon
      "
    networks:
      - horizon
  dispatcher:
    depends_on:
      migration:
        condition: service_completed_successfully
    restart: always
    build:
      context: .
      containerfile: Containerfile
    env_file:
      - .env
    command: |
      /bin/sh -c '
        set -e
        while sleep 5; do php artisan tinker --execute="\App\Jobs\ExampleJob::dispatch()"; done
      '
    networks:
      - horizon
  redis:
    image: redis:alpine
    restart: always
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - horizon

volumes:
  redis_data:
  mysqldata8:

networks:
  horizon:
