version: "3.7"

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./:/app/
    command: |
      /bin/bash -c "
        set -e
        php artisan serve --host 0.0.0.0 &
        php artisan horizon
      "

  redis:
    image: redis:alpine
    restart: always
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
